#!/bin/sh 

usage() {
cat << EOF
$(basename $0):
	-r receiver 	set other receiver
	-s sender	gtalk account
	-h 		show help
EOF
}

RECEIVER="Receiver Name" 		# default receiver
SENDER="gtalkaccount@gmail.com"		# default sender

while echo "$1" | grep -q "^\-\+\w" ; do
	for flag in `echo $1 | grep -o "\w"`; do
		if [ $flag = "r" ]; then
			RECEIVER="$2"
		elif [ $flag = "s" ]; then
			SENDER="$2"
		elif [ $flag = "h" ]; then
			usage
			exit 0
		else
			echo error args -$flag >&2
			usage
			exit 1
		fi
	done
	shift
	if [ "$SENDER" != "" ]; then
		shift
	fi
	if [ "$RECEIVER" != "" ]; then
		shift
	fi
done

export RECEIVER
export SENDER

if [ "$1" != "" ] ; then
	export CONTENT="$@"
else
	export CONTENT="`cat`"
fi

/usr/bin/osascript << EOF
on isRunning(appName)
	tell application "System Events" to (name of processes)  contains appName
end isRunning

on SendMessage()
	tell application "Messages"
		activate
		set recerBuddy to 0

		
		set myBuddies to {}
		repeat with myServ in services
			if name of myServ as string is "$SENDER" then
				set myBuddies to buddies of myServ
			end if
		end repeat


		repeat with bBuddy in myBuddies
			set bName to name of bBuddy
			set bId to id of bBuddy
			if bId ends with "google.com" and bName is equal to "$RECEIVER" then
				-- display dialog bName & " " & bId & " "
				set recerBuddy to bBuddy
				-- send "hello" to bBuddy
			end if
		end repeat
		
		if recerBuddy is not 0 then
			send "$CONTENT" to recerBuddy
		end if

		-- hide windows of "Messages"
		tell application "Finder" 
			set visible of application process "Messages" to false
		end tell
	end tell
end SendMessage

if not isRunning("Messages") then
	tell application "Messages"
		activate
		repeat with myServ in services
			if name of myServ as string is "$SENDER" then
				repeat while (status of myServ as string) is "offline"
					delay 0.5
				end repeat
			end if
		end repeat
		delay 2
	end tell
end if

SendMessage()
-- beep 5

EOF


